# Generated by Django 6.0 on 2025-12-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('data_lancamento', models.DateField()),
                ('descricao', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capa_games')),
            ],
        ),
    ]
