# Generated by Django 6.0 on 2025-12-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rank'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ranks',
            field=models.ManyToManyField(blank=True, related_name='players', to='games.rank'),
        ),
    ]
