# Generated by Django 6.0 on 2025-12-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='players',
            field=models.ManyToManyField(to='players.player'),
        ),
    ]
