# Generated by Django 6.0 on 2025-12-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0002_lobby_players'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='salas_que_estou', to='players.player'),
        ),
    ]
